spring:
  profiles:
    active: dev
  application:
    name: hilltop-api-gateway
  cloud:
    gateway:
      routes:
        - id: hilltop-user-service
          uri: http://hilltop-user-service.eu-north-1.elasticbeanstalk.com/
          predicates:
            - Path=/hilltop-user-service/**
          filters:
            - JwtAuthenticationFilter
        - id: hilltop-hotel-service
          uri: http://hilltop-hotel-service.eu-north-1.elasticbeanstalk.com/
          predicates:
            - Path=/hilltop-hotel-service/**
          filters:
            - JwtAuthenticationFilter
        - id: hilltop-reservation-service
          uri: http://hilltop-reservation-service.eu-north-1.elasticbeanstalk.com/
          predicates:
            - Path=/hilltop-reservation-service/**
          filters:
            - JwtAuthenticationFilter
        - id: hilltop-search-service
          uri: http://hilltop-reservation-service.eu-north-1.elasticbeanstalk.com/
          predicates:
            - Path=/hilltop-search-service/**
          filters:
            - JwtAuthenticationFilter
eureka:
  client:
    serviceUrl:
      defaultZone: http://hilltop-discovery-service.eu-north-1.elasticbeanstalk.com/eureka

server:
  port: 5000

userService:
  validateToken: http://hilltop-user-service.eu-north-1.elasticbeanstalk.com/hilltop-user-service/api/v1/user/validate-token?token=
